apiVersion: v1
kind: Pod
metadata:
  name: patsdogstatsd
spec:
  hostNetwork: true
  containers:
  - name: patsdogstatsd
    image: patsdogstatsd:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: DD_AGENT_HOST
      valueFrom:
          fieldRef:
              fieldPath: status.hostIP