apiVersion: v1
kind: Pod
metadata:
  name: patsudsdogstatsd
spec:
  hostPID: true
  containers:
  - name: patsudsdogstatsd
    image: patsudsdogstatsd:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: dsdsocket
      mountPath: /var/run/datadog
      readOnly: true
  volumes:
    - hostPath:
          path: /var/run/datadog/
      name: dsdsocket